version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: villa_mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: villa_db
    volumes:
      - villa_mysqldata:/var/lib/mysql

volumes:
  villa_mysqldata:
