version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: villa_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: villa_user
      POSTGRES_PASSWORD: villa_pass
      POSTGRES_DB: villa_db
    volumes:
      - villa_pgdata:/var/lib/postgresql/data

volumes:
  villa_pgdata:
